export const FETCH_GUESTBOOKS = 'FETCH_GUESTBOOKS';
export const CREATE_GUESTBOOK = 'CREATE_GUESTBOOK';
export const MENU_ORDERED = 'MENU_ORDERED';
export const FETCH_GUESTBOOK = 'FETCH_GUESTBOOK';
export const DELETE_GUESTBOOK = 'DELETE_GUESTBOOK';
export const USER_LOGIN = 'USER_LOGIN';
export const FETCH_LOGIN_GUESTBOOK = 'FETCH_LOGIN_GUESTBOOK';
